ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
app_name="cart"
from cart import views
urlpatterns = [
    path('<int:i>',views.addtocart,name="addtocart"),
    path('cartview',views.cart_view,name="cartview"),
    path('cart_remove/<int:i>',views.cart_remove,name="cart_remove"),
    path('cart_fullremove/<int:i>', views.cart_fullremove, name="cart_fullremove"),
    path('orderform',views.orderform,name="orderform"),
    path('payment-status<str:p>',views.payment_status,name="status"),
path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
path('search/',include('search.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('',views.searchproducts,name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
   path('',views.categories,name="categories"),
   path('products/<int:i>',views.products,name="products"),
   path('detail/<int:i>',views.productdetail,name="detail"),
   path('register', views.register, name="register"),
   path("login", views.user_login, name="login"),
   path("logout", views.user_logout, name="logout"),
   path('addcategories',views.addcategories,name="addcategories"),
path('addproducts',views.addproducts,name="addproducts"),
   path('addstock/<int:i>',views.addstock,name="addstock")

]

ecommerce/cart/models.py
from django.db import models


from shop.models import Product
from django.contrib.auth.models import User
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price*self.quantity

    def __str__(self):
        return self.product.name
class Order_details(models.Model):#for storing product details
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.BigIntegerField()
    pin=models.IntegerField()
    order_id=models.CharField(max_length=30)
    payment_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    ordered_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.order_id
class Payment(models.Model): #for storing payment details
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

    def __str__(self):
        return self.order_id

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
from cart.models import Cart

import razorpay
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)#if product is already present inside table for the current user
        c.quantity+=1  #it will increment the quantity inside the record
        p.stock-=1
        p.save()
        c.save()
    except: #if not present
        c=Cart.objects.create(product=p,user=u,quantity=1) #it will add a new record with quantity =1
        p.stock-=1
        p.save()
        c.save()

    return redirect('cart:cartview')


def cart_view(request):
    u=request.user
    c=Cart.objects.filter(user=u)  #to filter cart records for a particular user

    #to calculate Total value
    total=0
    for i in c:
         total=total+(i.quantity*i.product.price)

    context={'cart':c,'total':total}
    return render(request,'cart.html',context)

def cart_remove(request,i):
    u=request.user
    p=Product.objects.get(id=i)
    try:
        c=Cart.objects.get(user=u,product=p)
        if (c.quantity >1): #if cart quantity >0
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()
        else:  #if cart quantity =0
            c.delete()
            p.stock+=1
            p.save()
    except:
        pass
    return redirect('cart:cartview')

from cart.models import Payment,Order_details
def cart_fullremove(request,i):
    u = request.user
    p = Product.objects.get(id=i)
    try:
        c = Cart.objects.get(user=u, product=p)

        c.delete()
        p.stock += c.quantity
        p.save()
    except:
        pass
    return redirect('cart:cartview')



def orderform(request):
    if request.method=="POST":
        #Read input from the form fields
        a=request.POST['a']
        pn=request.POST['p']
        n=request.POST['n']

        #for calculating total bill amount
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.product.price*i.quantity

        print(total)
        #Razorpay client connection
        client=razorpay.Client(auth=('rzp_test_64QMU042Xkyl5V','ccRXcmzCs68MZULI0vKtxdua'))
        #Razorpay order creation
        response_payment=client.order.create(dict(amount=total*100,currency='INR'))
        print(response_payment)
        order_id=response_payment['id'] #retrieve the order id from response
        status=response_payment['status'] #retrieve the status from response
        #
        #
        if (status=="created"):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()

            for i in c:
                o=Order_details.objects.create(product=i.product,user=i.user,phone=pn,address=a,pin=n,order_id=order_id,no_of_items=i.quantity)
                o.save()

            context={'payment':response_payment,'name':u.username} #sends the response from view to payment.html

            return render(request,"payment.html",context)

    return render(request,'orderform.html')



from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import login
@csrf_exempt
def payment_status(request,p):

    user=User.objects.get(username=p) #retrieve user object
    login(request,user)
    #
    response=request.POST #razorpay response after successful payment
    print(response)

    #
    # #To Check the validity(authenticity) of razorpay payment details received by application
    param_dict={
        'razorpay_order_id':response['razorpay_order_id'],
        'razorpay_payment_id':response['razorpay_payment_id'],
        'razorpay_signature':response['razorpay_signature']
        }

    client = razorpay.Client(auth=('rzp_test_64QMU042Xkyl5V', 'ccRXcmzCs68MZULI0vKtxdua'))
    try:
        status=client.utility.verify_payment_signature(param_dict)   #for checking the payment details
                                                                    # we pass param_dict to verify_payment_signature function
        print(status)
        p=Payment.objects.get(order_id=response['razorpay_order_id'])
        p.paid=True
        p.razorpay_payment_id=response['razorpay_payment_id']
        p.save()

        o=Order_details.objects.filter(order_id=response['razorpay_order_id'])
        for i in o:
            i.payment_status="completed"
            i.save()

        c=Cart.objects.filter(user=user)
        c.delete()

    except:
        pass

    return render(request,'payment-status.html')

def orderview(request):
    u=request.user
    o=Order_details.objects.filter(user=u,payment_status="completed")
    context={'orders':o}
    return render(request,'orderview.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def searchproducts(request):
    p= None
    query = ""
    if (request.method == "POST"):
        query = request.POST['q']
        print(query)
        if query:
            p = Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))  # Inorder to add AND or OR logic into Django Queries here we use Q object
            # i->caseinsensive
            # contains-->anywhere inside the field
    context={'pro':p,'query':query}
    return render(request,'search.html',context)

ecommerce/templates/addcategories.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 p-3 bg-secondary" style="margin-bottom:100px;">
<h2>Add Category Details</h2>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Category name</label>
  <input type="text" class="form-control" name="n" placeholder="Enter Category">
</div>
        <div class="mb-3">
         <label  class="form-label">Image</label>
  <input type="file" class="form-control" name="i">
</div>
 <div class="mb-3">
  <label  class="form-label">Description</label>
  <textarea class="form-control" name="d"></textarea>
</div>
        <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>

    </div>
{% endblock %}

ecommerce/templates/addproducts.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 p-3 bg-secondary" style="margin-bottom:100px;">
<h2>Add Product Details</h2>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Category name</label>
  <input type="text" class="form-control" name="n" placeholder="Enter Category">
</div>
        <div class="mb-3">
         <label  class="form-label">Image</label>
  <input type="file" class="form-control" name="i">
</div>
 <div class="mb-3">
  <label  class="form-label">Description</label>
  <textarea class="form-control" name="d"></textarea>
</div>

        <div class="mb-3">
         <label  class="form-label">Stock</label>
  <input type="number" class="form-control" name="s">
</div>
        <div class="mb-3">
         <label  class="form-label">Price</label>
  <input type="number" class="form-control" name="p">
</div>
        <div class="mb-3">
         <label  class="form-label">Category</label>


            <select name="c" class="form-control">

                  {% for i in links %}
     <option value="{{i.name}}">{{i.name}}</option>
                {% endfor %}
 </select>

</div>


        <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>

    </div>
{% endblock %}

ecommerce/templates/addstock.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 p-3 bg-secondary" style="margin-bottom:100px;">
<h2 class="text-center">Add Product Stock</h2>

 <form method="POST" >
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Stock</label>
  <input type="number" value="{{pro.stock}}" class="form-control" name="n" placeholder="Enter new stock">
</div>



        <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>

    </div>



    </div>
{% endblock %}

ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 p-3" style="margin-bottom:100px;">
     <h2 class="text-center">Shopping Cart</h2>
<div class="row">

    <div class="col-7"><table class="table table-bordered text-dark fw-bold">
        <tr>
            <th colspan="7" class="text-center">Cart Items</th>
        </tr>

        {% for i in cart %}
        <tr>
            <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
            <td>{{i.product.name}}</td>
            <td>Unitprice:{{i.product.price}}<br>
            Quantity:{{i.quantity}}</td>
            <td>Subtotal:{{i.subtotal}}</td>

            <td>
                {% if i.product.stock > 0 %}
                <a href="{% url 'cart:addtocart' i.product.id  %}"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
            <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa fa-minus-circle " aria-hidden="true"></i></a>
            <a href="{% url 'cart:cart_fullremove' i.product.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
            {% else %}
                <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa fa-minus-circle" aria-hidden="true"></i></a>
            <a href="{% url 'cart:cart_fullremove' i.product.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}

    </table></div>
    <div class="col-4">
        <table class="table table-bordered text-center">
            <tr>
                <th colspan="4"  class="text-center">CheckOut</th>

            </tr>

            <tr>
                <td>Total:<b>{{total}}</b></td>
            </tr>
        </table>
        <div class="d-flex justify-content-between">
            <a href="{% url 'cart:orderform' %}" class="btn-dark p-2">Place Order</a>
            <a href="{% url 'shop:categories' %}" class="btn-dark p-2">Continue Shopping</a>
        </div>
    </div>
</div>





</div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>LOGIN</title>
    {% endblock %}
{% block content %}
<center>
    <div class="container mt-5 p-3 bg-dark text-light" style="margin-bottom:100px;color:white">
<h2 class="text-center text-light">Login here......</h2>
    <form method="post">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>
 <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>
        <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>
    {% if messages %}
<ul class="messages text-danger fs-4 text-capitalize">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </div>
{% endblock %}
</body>
</html>

ecommerce/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hello
</body>
</html>

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 p-3 bg-dark text-light" style="margin-bottom:100px;">
<h2 class="text-center text-light">Billing Details.</h2>

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Address</label>
 <textarea name="a" class="form-control">Write address here</textarea>
</div>
 <div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control" name="p" placeholder="Enter phonenumber">
</div>
     <div class="mb-3">
  <label  class="form-label">Pin</label>
  <input type="number" class="form-control" name="n" placeholder="Enter pinumber">
</div>




     <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>
 </div>


    </div>
{% endblock %}

ecommerce/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    <div class="container mt-5 p-3 bg-dark text-light" style="margin-bottom:100px;color:white">
     <h2 class="text-light text-center">Customer Name:{{user.username}}</h2>
      {% for i in orders %}
      <div class="card mb-3 mx-auto border border-1 border-danger" style="max-width: 900px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{i.product.image.url}}" class="rounded-start" height="200px" width="100%" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 class="card-title">Productname:<b>{{i.product.name}}</b></h4>
        <p class="card-text text-dark">Price:<b>{{i.product.price}}</b></p>
          <p class="card-text text-dark">NumberofItems:<b>{{i.no_of_items}}</b></p>
        <p class="card-text text-dark">Order_id:<b>{{i.order_id}}</b></p>
<p class="card-text text-dark">Ordered on:<b>{{i.ordered_date}}</b></p>
        <p class="card-text"><b class="text-danger">Delivery_status:{{i.delivery_status}}</b></p>
      </div>
    </div>
  </div>
</div>{% endfor %}
    </div>
{% endblock %}
</body>
</html>

ecommerce/templates/payment-status.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    <div class="container mt-5 p-3 bg-dark text-light" style="margin-bottom:100px;color:white">
     <h2 class="text-light">Payment Successful</h2>
    </div>
{% endblock %}
</body>
</html>

ecommerce/templates/payment.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    <div class="container mt-5 p-3 bg-dark text-light" style="margin-bottom:100px;color:white">
<form action="{% url 'cart:status' name %}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_64QMU042Xkyl5V" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="My Shop"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="blue"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>

</form>

    </div>
{% endblock %}
</body>
</html>

ecommerce/templates/products.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid mt-5 ms-0">
    <img src="{{cat.image.url}}" height="500px"  width="100%">
</div>


<div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>{{cat.name}}</h1>
                        <p>{{cat.desc}}</p>
                    </div>
                </div>
            </div>


            <div class="row special-list">
                {% for i in pro %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale"></p>
                            </div>
                            <img src="{{i.image.url}}" class="img-fluid" alt="Image">
                            <div class="mask-icon">

                                <a class="cart" href="{% url 'shop:detail' i.id %}">Details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{i.name}}</h4>
                            <h5> {{i.price}}</h5>
                        </div>
                    </div></div>
                    {% endfor %}
                </div>

<!--                <div class="col-lg-3 col-md-6 special-grid top-featured">-->
<!--                    <div class="products-single fix">-->
<!--                        <div class="box-img-hover">-->
<!--                            <div class="type-lb">-->
<!--                                <p class="new">New</p>-->
<!--                            </div>-->
<!--                            <img src="{% static 'images/img-pro-02.jpg' %}" class="img-fluid" alt="Image">-->
<!--                            <div class="mask-icon">-->
<!--                                <ul>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>-->
<!--                                </ul>-->
<!--                                <a class="cart" href="#">Add to Cart</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="why-text">-->
<!--                            <h4>Lorem ipsum dolor sit amet</h4>-->
<!--                            <h5> $9.79</h5>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-3 col-md-6 special-grid top-featured">-->
<!--                    <div class="products-single fix">-->
<!--                        <div class="box-img-hover">-->
<!--                            <div class="type-lb">-->
<!--                                <p class="sale">Sale</p>-->
<!--                            </div>-->
<!--                            <img src="{% static 'images/img-pro-03.jpg' %}" class="img-fluid" alt="Image">-->
<!--                            <div class="mask-icon">-->
<!--                                <ul>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>-->
<!--                                </ul>-->
<!--                                <a class="cart" href="#">Add to Cart</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="why-text">-->
<!--                            <h4>Lorem ipsum dolor sit amet</h4>-->
<!--                            <h5> $10.79</h5>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-3 col-md-6 special-grid best-seller">-->
<!--                    <div class="products-single fix">-->
<!--                        <div class="box-img-hover">-->
<!--                            <div class="type-lb">-->
<!--                                <p class="sale">Sale</p>-->
<!--                            </div>-->
<!--                            <img src="{% static 'images/img-pro-04.jpg' %}" class="img-fluid" alt="Image">-->
<!--                            <div class="mask-icon">-->
<!--                                <ul>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>-->
<!--                                </ul>-->
<!--                                <a class="cart" href="#">Add to Cart</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="why-text">-->
<!--                            <h4>Lorem ipsum dolor sit amet</h4>-->
<!--                            <h5> $15.79</h5>-->
<!--                        </div>-->
<!--                    </div>-->

        </div>
    </div>
    <!-- End Products  -->


{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    <div class="container mt-5 p-3 bg-dark text-light" style="margin-bottom:100px;">
<h2 class="text-center text-light">Register Here...</h2>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>
 <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>
     <div class="mb-3">
  <label  class="form-label">confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter confirm password">
</div>
        <div class="mb-3">
  <label  class="form-label">First_name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter First name">
</div>
     <div class="mb-3">
  <label  class="form-label">Last_name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter Last name">
</div>
    <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter email">
</div>

     <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>
 </div>
{% endblock %}
</body>
</html>

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    {% if pro == None %}
    <div class="container mt-5 p-3 bg-dark  text-light" style="margin-bottom:100px;color:white">

<h2 class="text-center text-light">Search Products</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" class="form-control" name="q">
                <input type="submit" class="btn btn-secondary">
            </div>
        </form>

    </div>
    {% else %}
   <div class="row special-list">
                {% for i in pro %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale"></p>
                            </div>
                            <img src="{{i.image.url}}" class="img-fluid" alt="Image">
                            <div class="mask-icon">

                                <a class="cart" href="{% url 'shop:detail' i.id %}">Details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{i.name}}</h4>
                            <h5> {{i.price}}</h5>
                        </div>
                    </div></div>


       {% empty %}
       <h2 class="text-center">No Results found</h2>
        {% endfor %}
                </div>
{% endif %}

</center></div>
{% endblock %}
</body>
</html>